# Generated by Django 5.0 on 2024-01-06 13:01

from django.db import migrations
from base.models import User

def create_deleted_user(apps, schema_editor):
    deleted_user = User.objects.create_user("deleted")
    deleted_user.set_unusable_password()
    deleted_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_wine_name'),
    ]

    operations = [
        migrations.RunPython(create_deleted_user),
    ]
